### ISSUE TITLE
`TagName` documentation mentions non-existant instance

### ISSUE THREAD

**Issue by rpglover64** [fimad/scalpel#10]
The [docs](https://github.com/fimad/scalpel/blob/master/src/Text/HTML/Scalpel/Internal/Select/Types.hs#L42) for `TagName` say "The most basic types of 'TagName' are the string like types (e.g.  'String', 'T.Text', etc). Values of these types refer to tags of the given value." However, there is no `instance TagName Text`.

**Comment by fimad** [comment]
Ah, thanks for catching that! That use to be the case but it didn't play well with overloaded strings, so it was removed in version 0.2.0.

I will update the documentation to reflect the actual types.
