### ISSUE TITLE
html stream should be decoded before calling TagSoup's parseTags

### ISSUE THREAD

**Issue by davire** [fimad/scalpel#11]
I need to work on a page encoded in utf-8 that also have html entities. The problem is that in that case entities aren't converted to their utf-8 encoded representation; as a result I don't know how to recover all special characters on the page.

The problem comes from the fact that TagSoup converts html entities to their unicode code point equivalent; but scalpel doesn't pass a decoded string to TagSoup.

A small example:

    Prelude Data.ByteString.Char8 Text.HTML.TagSoup> parseTags (pack "test\xC3\xA9 &#233; hop") :: [Tag ByteString]
    [TagText "test\195\169 \233 hop"]

The resulting string mixes utf-8 and unicode code points.

* \195\169 is the "é" character encoded in utf-8
* \233  is the "é" character unicode code point.

To work around it I would need to be able to decode the text from utf-8 in downloadAsTags

    downloadAsTags url = do
            maybeBytes <- openURIWithOpts url options
            return $ (TagSoup.parseTags . decodeEncoding . TagSoup.castString) <$> maybeBytes
    decodeEncoding = undefined  -- to be done, how ?

**Comment by davire** [comment]
If anyone has the same problem,  I've worked around it by using a modified scrapeURL :

    myScrapeURL :: String -> Scraper Text a -> IO (Maybe a)
    myScrapeURL url scraper = do
        maybeTags <- downloadAsTags url
        return (maybeTags >>= scrape scraper)
        where
            downloadAsTags url = do
                maybeBytes <- openURIWithOpts url [Curl.CurlFollowLocation True]
                return $ (TagSoup.parseTags . TagSoup.castString) <$> maybeBytes

    openURIWithOpts :: URL -> [Curl.CurlOption] -> IO (Maybe Text)
    openURIWithOpts url opts = do
        resp <- curlGetResponse_ url opts
        return $ if Curl.respCurlCode resp /= Curl.CurlOK
            then Nothing
            else Just $ T.decodeUtf8 $ Curl.respBody resp

    curlGetResponse_ :: URL
                 -> [Curl.CurlOption]
                 -> IO (Curl.CurlResponse_ [(String, String)] ByteString)
    curlGetResponse_ = Curl.curlGetResponse_

I.E I've added a T.decodeUtf8 in openURIWithOpts

**Comment by fimad** [comment]
Is the problem that you end up with a response where the same character is encoded in different ways?

Can you think of any reason no to run the output of openURIWithOpts through decodeUtf8 by default?

**Comment by davire** [comment]
Yes, the problem is that I end up with the same character encoded in different ways.

Unfortunately, there are pages that are not utf-8 encoded, so I don't think running the output of openURIWithOpts through decodeUtf8 by default is the right solution.

I see two ways :

* Look for a `<meta http-equiv="Content-Type" content="... ; charset=...">`  tag or a content-type response header and decode the output accordingly 
* Let the user provide a function that the response is run through.

**Comment by fimad** [comment]
I like the idea of passing in a decode function since it seems less brittle than trying to guess the encoding based on meta tags. 

I'm not sure what the best way to expose that would be though without breaking the existing API. It seems overly verbose to keep adding new functions like scrapeURLWithOptsAndDecoder. Maybe it is time to create a record type for extra settings that can be passed to scrapeURL.

**Comment by 5outh** [comment]
Would it be possible to tack on an extra field to the `Opts` and modify the defaults?
