### ISSUE TITLE
how to use attrs combinator

### ISSUE THREAD

**Issue by levinotik** [fimad/scalpel#2]
Not sure this should be an issue as much as a question, but I'm trying to get the value of all src attributes for img tags from a page. I'm trying something like this:

```haskell
pageImgSources :: String -> IO (Maybe [Text])
pageImgSources url = scrapeURL url $ attrs (pack "src") $ (pack "img")
```

But seem to come up with `Nothing` every time. Would you mind giving me a pointer on this?

Thanks for this great library!

**Comment by levinotik** [comment]
eh, it looks like that actually works fine. I guess certain sites are just blocking scrapers?

**Comment by fimad** [comment]
That should work, I just fired up this in GHCi:

ghci> scrapeURL "https://github.com" $ attrs (pack "src") $ (pack "img")
Just ["https://assets-cdn.github.com/images/modules/aws/cloud-1.png","https://assets-cdn.github.com/images/modules/aws/cloud-2.png","https://assets-cdn.github.com/images/modules/aws/cloud-3.png","https://assets-cdn.github.com/images/modules/aws/cloud-4.png","https://assets-cdn.github.com/images/modules/aws/cloud-5.png","https://assets-cdn.github.com/images/modules/aws/cloud-6.png"]

I think by default, the curl library scalpel users to download pages doesn't follow redirects. Can you check if the URL you are hitting is returning a 3XX redirect?

You can run `curl -v http://example.com` from the command line to check the headers of the response.

I can update scrapeURL to follow redirects, seems like that should be the expected default behavior.

**Comment by levinotik** [comment]
Thanks a lot. Looks like I found that out as you were writing it :) Having a lot of fun writing [this little service](https://github.com/grasswire/scrapey) with scalpel. 

Thanks again for your help.

**Comment by fimad** [comment]
Nice! It's exciting to see this getting used in other projects!

**Comment by fimad** [comment]
Also, re-opening, this looks like a legit bug. <img> tags aren't getting scraped properly if they do not include a trailing /.

ghci> scrapeStringLike "<img src='foobar'>" (attr "src" $ ("img" :: String))
Nothing
ghci> scrapeStringLike "<img src='foobar' />" (attr "src" $ ("img" :: String))
Just "foobar"
ghci>
