### ISSUE TITLE
Expose function to construct AttributePredicate generally

### ISSUE THREAD

**Issue by rpglover64** [fimad/scalpel#22]
It would be nice to have a function `match :: (String -> String -> Bool) -> AttributePredicate` for maximum flexibility.

There are, of course, other potential types, such as `match :: (forall str. StringLike str => Attribute str -> Bool) -> AttributePredicate`, but the simplest one seems like a good start.

**Comment by fimad** [comment]
Didn't realize this was missing, this should definitely be added.

**Comment by rpglover64** [comment]
This could be just exposing the constructor, right? Is there a reason that it's hidden?

In that same vein I'd suggest exposing the `Internal` modules; if someone wants to get around a short-coming of the public interface while risking backwards compatibility, I don't think the library should get in their way.

**Comment by fimad** [comment]
Going with `match` with strings as opposed to exposing the constructor since the constructor is a bit hairy.

**Comment by fimad** [comment]
Released in 0.3.1
