### ISSUE TITLE
would like to select based on the text of a node

### ISSUE THREAD

**Issue by gregnwosu** [fimad/scalpel#25]
try as I might I havent been able to select based on the text, further more the text primitive seems to concatenate all text nodes beneath the current node. Any ways around this?

**Comment by rpglover64** [comment]
Check out the response to issue #23 

``` haskell
chroots "p" $ do
  t <- text Any
  guard (isInfixOf "would" t)
  html Any
```
selects paragraphs whose text contains "would".

**Comment by fimad** [comment]
Does @rpglover64's comment provide what you need?

As for concatenating all text nodes, I'm not sure what a reasonable alternative would be. For example, if you have `<a> foo <b> bar </b> baz </a>` there isn't a single text node within the `<a>` tag. And it seems like it would be very unintuitive to only return `foo baz` in this case.

**Comment by fimad** [comment]
Closing this out. The chroots trick @rpglover64 provided is now documented in the README.
