### ISSUE TITLE
Scraper for inner HTML

### ISSUE THREAD

**Issue by LukaHorvat** [fimad/scalpel#26]
Currently there's the `text` scraper that grabs the textual content of the selected node, and there's the `html` scraper that get's the whole selected node. I'd like a scraper that gives me only the inner HTML, without the selected tag itself.

**Comment by fimad** [comment]
What would that return for something like ` <a> foo <b> bar </b> baz </a> `?

Would it be `foo <b> bar </b> baz` or `<b> bar </b>`?

**Comment by LukaHorvat** [comment]
The former.

**Comment by fimad** [comment]
This has been released in 0.3.1
