### ISSUE TITLE
Hard to use scalpel with OverloadedStrings enabled.

### ISSUE THREAD

**Issue by debug-ito** [fimad/scalpel#29]
Related to: #4

As of scalpel-0.3.0.1, it's hard to use with OverloadedStrings enabled.

As explained in #4, the reason is that GHC cannot figure out the concrete type for string literals for `Selectable`, `AttributeName` and `TagName` classes. As a result, we always have to specify the type (e.g., `("div" :: String)`).

One solution to this problem is to remove `Selectable` class and make `Selector` an instance of `IsString`.

```haskell
data Selector = ...

tagSelector :: String -> Selector
tagSelector tag = tag @: []

-- | Substitute for 'Any'.
anySelector :: Selector
anySelector = ...

instance IsString Selector where
  fromString = tagSelector
```

and then

```haskell
(//) :: Selector -> Selector -> Selector 
```

That way, we always deal with the concrete type `Selector`. With OverloadedStrings enabled, we can use a string literal for `Selector`.

The same goes for `TagName` and `AttributeName` classes. For those classes, we have to introduce corresponding data types, though.

Downsides of this approach are:

- It destroys backward-compatibility. So if I were to do that, I would make a new module for this new API. The API of `Text.HTML.Scalpel` would stay, but its implementation would be rewritten.
- This new API may be hard to use WITHOUT OverloadedStrings, compared with the current API. It's OK for me. I almost always use OverloadedStrings.

**Comment by aupiff** [comment]
@fimad let's close this issue.
