### ISSUE TITLE
Keeping HTML after scraping

### ISSUE THREAD

**Issue by sportanova** [fimad/scalpel#3]
I'm having a lot of fun getting to know scalpel! I was wondering - is there a way to run the Scraper but still keep the html (not just take the inner text)?

**Comment by fimad** [comment]
Not currently, but we could easily expose that.

**Comment by sportanova** [comment]
How about adding an "html" function that will correspond to the "text" function. It'll internally make a call to "tagsToHtml"  (like how "text" uses a "tagsToText"). Mind if I take a crack at a pull request? I'll add a test case too

**Comment by fimad** [comment]
Sounds great!

**Comment by sportanova** [comment]
just did https://github.com/fimad/scalpel/pull/5

let me know any comments / things I can change!
