### ISSUE TITLE
Figure out story for queries that span multiple sub-trees.

### ISSUE THREAD

**Issue by fimad** [fimad/scalpel#48]
Right now scalpel makes the assumption that an HTML document is a tree (possibly a malformed one) and that scraping involves selecting one or more sub-trees and extracting (the same) data from each sub-tree.

There are use cases (#41, #45) that don't fit into this model but would nice to support.

This issue is for brainstorming API/architecture changes that would support these types of queries.
#41 could be solved by extending selectors to allow jumping between sibling sub-trees, maybe something that looked like:

``` html
<p class="something">Here</p>
<p>Other stuff that matters</p>
```

``` haskell
chroot "p" @: [hasClass "something"] $ do
  here <- text AnyTag
  otherStuff <- text $ rightSibling "p"
```

The problem with this is that it doesn't really extend to more complicated scenarios like those #45 which involves collecting a sequence of siblings until a certain condition is met.

**Comment by fimad** [comment]
It seems like both of these may be solvable if we were able to insert new fake nodes into the tag tree.

What if there was a `group`/`groups` scraper that took a list of selectors and created a new tree where each selector in the list was a child.

### #41

```html
<p class="something">Here</p>
<p>Other stuff that matters</p>
```

```haskell
[
  "Here", 
  "Other stuff that matters"
] <- group ["p" @: [hasClass "something"], "p"] texts
```

### #45

```html
<body>
  <h1>title1</h1>
  <h2>title2 1</h2>
  <p>text 1</p>
  <p>text 2</p>
  <h2>title2 2</h2>
  <p>text 3</p>
  <h2>title2 3</h2>
</body>
```

```haskell
[
  ("title2 1", ["text 1", "text 2"]),
  ("title2 2", ["text 3"]),
  ("title2 3", []),
] <- chroot "body" $ do
  groups ["h2", many "p"] $ do
    title <- text "h2"
    body  <- texts "p"
    return (title, body)
```

**Comment by 3noch** [comment]
It'd also be very useful to refer to siblings that have naked text (i.e. not part of a subtree).

**Comment by ocramz** [comment]
@3noch @fimad I think I just encountered one such edge case: I have a bit of HTML like the following : 

```
<h2 class="...">
    <span class="...">
               .... 
    </span>
    info
</h2>
```
And I just need to retrieve `info` (or rather, ignore the `span`).

**Comment by 3noch** [comment]
The workaround for now is to select the `h2` and use `position` IIRC.

**Comment by fimad** [comment]
Unfortunately I don't think `position` would help with that example since there is currently no way to select bare text nodes. One of the assumptions scalpel makes is that anything you'd want to select is between `<tags>`.

It's also not immediately clear how to expose bare text selection in a way that would be backwards compatible. My current thinking is to create an additional value for [SelectNode](https://github.com/fimad/scalpel/blob/master/scalpel-core/src/Text/HTML/Scalpel/Internal/Select/Types.hs#L71) for text nodes. That would let you do something like the following to grab the second text node under an `<h2>`:

```haskell
chroot "h2" $ 
  chroots textSelector $ do
    p <- position
    guard (p == 1)
    text textSelector
```

With an API like the one proposed in #21 you could do something even more snazzy like: `text ("h2" /// textSelector)` to grab just the text nodes that are direct children of the `<h2>`.

The potential issue here though is that allowing selection of bare text nodes would create a breaking change in the behavior of `anySelector`. For example, `scrapeStringLike "<a>text</a>" $ texts anySelector` currently returns `Just ["text"]` but if we treated each text node as selectable then it would return `Just ["text", "text"]`.

This might be an OK breaking change though since I think the most useful use of `anySelector` is to select the current root node in a `chroot` block like the [examples](https://github.com/fimad/scalpel#complex-predicates) in the read me.

**Comment by fimad** [comment]
Was starting to look into this and I'm now thinking of trying to do the following:

Have some way to toggle the behavior of `Scraper` so that instead of starting from the current root, each subsequent scraper would only "see" the first child of the current context and child would be "consumed" on a match. This could be toggled with a new function `serial :: Scraper a -> Scraper a`.

### #41

``` html
<p class="something">Here</p>
<p>Other stuff that matters</p>
```

``` haskell
("Here", "Other stuff that matters") <- serial $ do
  first <- text "p" @: [hasClass "something"]
  second <- text "p"
  (first, second)
```

### #45

``` html
<body>
  <h1>title1</h1>
  <h2>title2 1</h2>
  <p>text 1</p>
  <p>text 2</p>
  <h2>title2 2</h2>
  <p>text 3</p>
  <h2>title2 3</h2>
</body>
```

``` haskell
[
  ("title2 1", ["text 1", "text 2"]),
  ("title2 2", ["text 3"]),
  ("title2 3", []),
] <- chroot "body" $ serial $ many $ do
    title <- text "h2"
    body <- many $ text "p"
    return (title, body)
```

Some details that still need to be worked out are how to treat nested matches. Should the next scraper pick up from the sibling of the root or the match? For example:

```html
<a>
  <b>1</b>
  <c>2</c>
</a>
<c>3</c>
```

```haskell
serial $ do
  "1" <- text "a" // "b"
  foo <- text "c"
```

Should `foo` be `"2"` or `"3"`?

Let's say you wanted to select all 3 values. This would be supported by each case:

Start from the sibling of the root of the match:

```haskell
serial $ do
  ("1", "2") <- chroot "a" $ (,) <$> text "b" <*> text "c"
  "3" <- text "c"
```

Start from the sibling of the leaf of the match:

```haskell
serial $ do
  "1" <- text "b"
  "2" <- text "c"
  "3" <- text "c"
```

Starting from the root is more verbose, but also requires the user to be more precise about the structure of the match.

**Comment by fimad** [comment]
Ended up going with a solution similar to that proposed [above](https://github.com/fimad/scalpel/issues/48#issuecomment-462097248) where only the immediate children are visited.

The solution utilizes a new type `SerialScraper` where the user explicitly moves the cursor with functions like `stepNext` and `seekNext`.
