### ISSUE TITLE
Example issue.

### ISSUE THREAD

**Issue by rlpowell** [fimad/scalpel#6]
It took me A While to figure out why the example wasn't returning anything in ghci.

Turns out that unless you give a Show instance for Comment, ghci silently returns when you run allComments.  Here's a complete, working version (assuming the URL has the html in question):

      import Text.HTML.Scalpel
      import Control.Applicative
      
      type Author = String
      
      data Comment
          = TextComment Author String
          | ImageComment Author URL
          deriving (Show, Eq)
      
      allComments :: IO (Maybe [Comment])
      allComments = scrapeURL "http://vrici.lojban.org/~rlpowell/media/public/test.html" comments
         where
             comments :: Scraper String [Comment]
             comments = chroots ("div" @: [hasClass "container"]) comment
      
             comment :: Scraper String Comment
             comment = textComment <|> imageComment
      
             textComment :: Scraper String Comment
             textComment = do
                 author      <- text $ "span" @: [hasClass "author"]
                 commentText <- text $ "div"  @: [hasClass "text"]
                 return $ TextComment author commentText
      
             imageComment :: Scraper String Comment
             imageComment = do
                 author   <- text       $ "span" @: [hasClass "author"]
                 imageURL <- attr "src" $ "img"  @: [hasClass "image"]
                 return $ ImageComment author imageURL
      
Giving:

      Prelude> :load scalpel.hs
      [1 of 1] Compiling Main             ( scalpel.hs, interpreted )
      Ok, modules loaded: Main.
      *Main> allComments
      Just [TextComment "Sally" "Woo hoo!",ImageComment "Bill" "http://example.com/cat.gif",TextComment "Susan" "WTF!?!"]
      *Main>

**Comment by fimad** [comment]
Thanks for point this out!

I've updated the documentation and released version 0.2.0.1 with the updates. I've also added an examples folder with several ready to compile example programs.

**Comment by rlpowell** [comment]
Frankly, I think the *total silence* is GHCI's issue more than yours, but thank you for fixing it.  :)
