### ISSUE TITLE
[Question] Why the Ord constraint on Selector types?

### ISSUE THREAD

**Issue by ocramz** [fimad/scalpel#61]
I'm looking in particular at the primitives that consume selectors, such as `text` and `html`

**Comment by fimad** [comment]
I *think* `Ord` is not actually needed anymore.

As part of parsing an HTML document [a map is created where the keys are tags](https://github.com/fimad/scalpel/blob/master/scalpel-core/src/Text/HTML/Scalpel/Internal/Select.hs#L114). In the latest version, the keys are always cast to `Text` but I think earlier versions used the underlying `StringLike` type of the document.

**Comment by fimad** [comment]
This constraint has been removed in version `0.6.0`.
