### ISSUE TITLE
How to use (@=~)?

### ISSUE THREAD

**Issue by luntain** [fimad/scalpel#64]
It looks like a convenience operator but I don't see how to use it easily. The RegexLike instance in Text.Regex.TDFA.String wants Regex, which is not convenient to create. How do you mean it to be used? I came up with the following after a fair deal of browsing the docs:

```
import Text.Regex.TDFA
import Text.Regex.TDFA.String (compile)

  let re = forceRight $ compile defaultCompOpt defaultExecOpt "b*"
  sym <- text ("a" @: ["href" @=~ re])
```

**Comment by fimad** [comment]
To be honest, I haven't used that operator since I first wrote this library so I don't remember the original rationale for the type signature.

I did find a slightly simpler example of how it is used in the unit tests:

```haskell

import qualified Text.Regex.TDFA

re :: String -> Text.Regex.TDFA.Regex
re = Text.Regex.TDFA.makeRegex

value <- text ("a" @: ["key" @=~ re "va(foo|bar|lu)e"])
```

**Comment by luntain** [comment]
thx
