### ISSUE TITLE
(a -> Maybe b) -> Scraper str a -> Scraper str b

### ISSUE THREAD

**Issue by madjar** [fimad/scalpel#8]
Thanks to the Functor instance, it is easy to process the result of a scraper to get another scraper. However, I could not find any way to do it with a processing that might fail.

Use case: I read some integer value from an attribute that I convert to Int, and I'd like it to fail gracefully.

    read <$> attr "data-count" "div"  -- Exception when there's no parse

What I'd like

    read <$?> attr "data-count" "div"  -- The scrapper returns Nothing when there's no parse

The implementation is simple provided access to MkScraper (which is internal). The hard part is finding the right function name or the right symbol :)

**Comment by fimad** [comment]
The `Alternative` instance should give you enough to implement `<$?>` without accessing internal state:

    (<$?>) :: (a -> Maybe b) -> Scraper str a -> Scraper str b
    (<$?>) f scraper = (f <$> sraper) >>= maybe empty return

I'm unsure if it would make sense for scalpel to export `<$?>` given that this is more ore less a special case of [guard, and friends](https://hackage.haskell.org/package/base-4.8.0.0/docs/Control-Monad.html#g:6)

I think it may make more sense to make `Scraper` an instance of [MonadError](https://hackage.haskell.org/package/mtl/docs/Control-Monad-Error-Class.html) and try to have it automatically handle these failure cases without the need for a special operator.

**Comment by madjar** [comment]
Oh, thanks, I hadn't though about it this way. Guess I just learned to recognize and use an Alternative :)

Seen that way, it wouldn't indeed make sense for this operator to be in scalpel.

For the trivia, the left part of the definition (`maybe empty return`) can be found in several places under names like `hoistMaybe`, `justZ` and `liftMaybe`. The function I wanted can be found in a specialized form as `mapMaybe` in base or `mapFilterE` in yampa.

Thanks !
