### ISSUE TITLE
scalpel-core and scalpel have been removed from stackage

### ISSUE THREAD

**Issue by debug-ito** [fimad/scalpel#85]
scalpel-core and scalpel packages have been remove from stackage. Check the  [build-constraints.yaml](https://github.com/commercialhaskell/stackage/blob/master/build-constraints.yaml).

Comment in the build-constraints.yaml says there is "compilation error" for scalpel-core. Could you fix it?

**Comment by fimad** [comment]
Thanks for the heads up!

I have a [PR](https://github.com/commercialhaskell/stackage/pull/5081) out to re-enable scalpel in stackage.

**Comment by debug-ito** [comment]
OK, they are now included in stackage nightly.
