### ISSUE TITLE
<|> is defined in hidden module

### ISSUE THREAD

**Issue by epoberezkin** [fimad/scalpel#89]
I may be wrong, but "Text.HTML.Scalpel.Internal.Scrape" (where Alternative instance is defined) is not exposed?

**Comment by fimad** [comment]
`<|>` is defined by the `Control.Applicative` module. If you want access to that operator you'll need to import that module. Check out [this file](https://github.com/fimad/scalpel/blob/master/examples/example-from-documentation/Main.hs) for an example.

**Comment by epoberezkin** [comment]
thank you :)
