### ISSUE TITLE
Expose internals of AttributePredicate

### ISSUE THREAD

**Issue by isovector** [fimad/scalpel#93]
I'd like to write a selector that can match on any class that contains a particular word. The exposed interface to scalpel isn't sufficient to accomplish this, but it's clear that the internals are capable.

**Comment by fimad** [comment]
I think you could achieve that with either `match` which lets you create arbitrary attribute predicates or `(@=~)` which allows you to specify a regex for matching attribute values.

https://hackage.haskell.org/package/scalpel-core-0.6.2/docs/Text-HTML-Scalpel-Core.html#g:4
